### ISSUE TITLE
not working after last updat using Firefox

### ISSUE THREAD

**Issue by dePaauw** [Emurasoft/excel-csv-import-help#8]
We are using this plugin on a Linux server using Firefox to login to Office to edit .csv files correctly.
It was all working perfectly until the last update, the plugin is now grey-ed out and unable to function.
![Schermafdruk van 2023-11-26 17-49-35](https://github.com/Emurasoft/excel-csv-import-help/assets/152086493/ca16ff14-50fe-4694-9918-11687f427f10)

**Comment by MakotoE** [comment]
This was an issue last week but not anymore. I believe you have the old manifest file. In the Home tab, could you open the Add-ins dialog and click refresh? You may also need to reopen Excel.
![image](https://github.com/Emurasoft/excel-csv-import-help/assets/36318069/f67abf58-7059-4d9f-9392-a2ddb6e4c2e3)

**Comment by egemenft** [comment]
Still not working on me. The pop up opened on the browser not on the excel
![excel](https://github.com/Emurasoft/excel-csv-import-help/assets/155898706/c215dc0e-b9f2-41db-bd0b-46ab6c7efb52)

**Comment by MakotoE** [comment]
Try uninstalling, then reinstalling CSV Import+Export.
<img width="513" alt="Screenshot 2024-01-07 162157" src="https://github.com/Emurasoft/excel-csv-import-help/assets/36318069/89d0fa64-0984-4f6d-8e47-4c8167dd3232">
